// ============================================================
// Katalog evropskih živil in pijač (500+ artiklov)
// ============================================================
// Kategorizirano po tipih živil, z enotami, dobavitelji in
// minimalnimi količinami za slovenske restavracije.
// ============================================================

export interface CatalogItem {
  name: string;
  unit: string; // "kos" | "kg" | "l" | "g" | "ml"
  category: string;
  minQuantity: number;
  costPerUnit: number; // povprečna EUR cena
  supplier: string;
}

export const FOOD_CATALOG: CatalogItem[] = [
  // === MESO IN MESNINE ===
  { name: "Goveje meso (ram)", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 12.0, supplier: "Jata" },
  { name: "Goveje meso (vrat)", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 10.0, supplier: "Jata" },
  { name: "Goveje meso (rostbif)", unit: "kg", category: "meso", minQuantity: 3, costPerUnit: 22.0, supplier: "Jata" },
  { name: "Goveji file (biftek)", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 35.0, supplier: "Jata" },
  { name: "Goveja juša (kosti)", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 4.0, supplier: "Jata" },
  { name: "Svinjsko meso (ventil)", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 8.0, supplier: "Jata" },
  { name: "Svinjsko meso (plečka)", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 7.5, supplier: "Jata" },
  { name: "Svinjska pečenica", unit: "kg", category: "meso", minQuantity: 3, costPerUnit: 9.0, supplier: "Jata" },
  { name: "Svinjski vrat", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 7.0, supplier: "Jata" },
  { name: "Svinjska mast", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 4.5, supplier: "Jata" },
  { name: "Svinjski ocvirki", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 5.0, supplier: "Jata" },
  { name: "Piščanec (cel)", unit: "kos", category: "meso", minQuantity: 10, costPerUnit: 6.5, supplier: "Perutnina Ptuj" },
  { name: "Piščančje prsi (file)", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 8.5, supplier: "Perutnina Ptuj" },
  { name: "Piščančja bedra", unit: "kg", category: "meso", minQuantity: 5, costPerUnit: 5.5, supplier: "Perutnina Ptuj" },
  { name: "Piščančja krila", unit: "kg", category: "meso", minQuantity: 3, costPerUnit: 4.0, supplier: "Perutnina Ptuj" },
  { name: "Piščančji nuggets", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 7.0, supplier: "Perutnina Ptuj" },
  { name: "Turčija (cel)", unit: "kos", category: "meso", minQuantity: 2, costPerUnit: 25.0, supplier: "Perutnina Ptuj" },
  { name: "Race (cel)", unit: "kos", category: "meso", minQuantity: 2, costPerUnit: 15.0, supplier: "Jata" },
  { name: "Kranjska klobasa", unit: "kos", category: "meso", minQuantity: 10, costPerUnit: 3.5, supplier: "Jata" },
  { name: "Bežolska klobasa", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 8.0, supplier: "Jata" },
  { name: "Debela klobasa", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 9.0, supplier: "Jata" },
  { name: "Salama (polutrna)", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 11.0, supplier: "Jata" },
  { name: "Prašut (slovenski)", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 25.0, supplier: "Kraški" },
  { name: "Pančeta", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 12.0, supplier: "Jata" },
  { name: "Slanina", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 8.0, supplier: "Jata" },
  { name: "Šunka (kuhana)", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 10.0, supplier: "Jata" },
  { name: "Šunka (pršut)", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 18.0, supplier: "Kraški" },
  { name: "Mleto meso (mešano)", unit: "kg", category: "meso", minQuantity: 3, costPerUnit: 7.5, supplier: "Jata" },
  { name: "Mleto meso (goveje)", unit: "kg", category: "meso", minQuantity: 3, costPerUnit: 9.0, supplier: "Jata" },
  { name: "Ćevapčiči (surovi)", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 8.5, supplier: "Jata" },
  { name: "Pleskavica (surova)", unit: "kos", category: "meso", minQuantity: 20, costPerUnit: 1.5, supplier: "Jata" },
  { name: "Dobeljski zrezek", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 14.0, supplier: "Jata" },
  { name: "Dunajski zrezek", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 13.0, supplier: "Jata" },
  { name: "Telečje meso", unit: "kg", category: "meso", minQuantity: 2, costPerUnit: 18.0, supplier: "Jata" },
  { name: "Jagnjetina", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 16.0, supplier: "Jata" },
  { name: "Divjačina (govedo)", unit: "kg", category: "meso", minQuantity: 1, costPerUnit: 20.0, supplier: "Lovska zveza" },

  // === RIBE IN MORSKI SADEŽI ===
  { name: "Brancin", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 18.0, supplier: "Ribarnica" },
  { name: "Orada", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 16.0, supplier: "Ribarnica" },
  { name: "Tuna (file)", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 25.0, supplier: "Ribarnica" },
  { name: "Losos (file)", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 18.0, supplier: "Ribarnica" },
  { name: "Somon (surov)", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 22.0, supplier: "Ribarnica" },
  { name: "Sardine", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 8.0, supplier: "Ribarnica" },
  { name: "Inćuni", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 12.0, supplier: "Ribarnica" },
  { name: "Školjke", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 6.0, supplier: "Ribarnica" },
  { name: "Dagnje", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 5.0, supplier: "Ribarnica" },
  { name: "Kalamari (lignji)", unit: "kg", category: "ribe", minQuantity: 2, costPerUnit: 10.0, supplier: "Ribarnica" },
  { name: "Kozice (velike)", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 18.0, supplier: "Ribarnica" },
  { name: "Kozice (majhne)", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 12.0, supplier: "Ribarnica" },
  { name: "Hobotnica", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 15.0, supplier: "Ribarnica" },
  { name: "Polži (morski)", unit: "kg", category: "ribe", minQuantity: 1, costPerUnit: 14.0, supplier: "Ribarnica" },
  { name: "Tuna (v konzervi)", unit: "kos", category: "ribe", minQuantity: 10, costPerUnit: 2.5, supplier: "Mercator" },

  // === ZELENJAVA ===
  { name: "Krompir", unit: "kg", category: "zelenjava", minQuantity: 20, costPerUnit: 0.6, supplier: "Local" },
  { name: "Krompir (mladi)", unit: "kg", category: "zelenjava", minQuantity: 10, costPerUnit: 1.2, supplier: "Local" },
  { name: "Čebula (rumena)", unit: "kg", category: "zelenjava", minQuantity: 10, costPerUnit: 0.8, supplier: "Local" },
  { name: "Čebula (rdeča)", unit: "kg", category: "zelenjava", minQuantity: 5, costPerUnit: 1.0, supplier: "Local" },
  { name: "Česen", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 4.0, supplier: "Local" },
  { name: "Korenje", unit: "kg", category: "zelenjava", minQuantity: 5, costPerUnit: 0.7, supplier: "Local" },
  { name: "Peteršilj (korenina)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 1.5, supplier: "Local" },
  { name: "Zelena (stebla)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.0, supplier: "Local" },
  { name: "Paradižnik (navadni)", unit: "kg", category: "zelenjava", minQuantity: 5, costPerUnit: 1.5, supplier: "Local" },
  { name: "Paradižnik (cherry)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 3.0, supplier: "Local" },
  { name: "Paradižnik (pelati)", unit: "kos", category: "zelenjava", minQuantity: 10, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Paradižnikova omaka (passata)", unit: "l", category: "zelenjava", minQuantity: 5, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Paradižnikova koncentrat", unit: "kos", category: "zelenjava", minQuantity: 10, costPerUnit: 0.8, supplier: "Mercator" },
  { name: "Paprika (rdeča)", unit: "kg", category: "zelenjava", minQuantity: 3, costPerUnit: 2.5, supplier: "Local" },
  { name: "Paprika (zelena)", unit: "kg", category: "zelenjava", minQuantity: 3, costPerUnit: 2.0, supplier: "Local" },
  { name: "Paprika (rumena)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.5, supplier: "Local" },
  { name: "Paprika (feferoni)", unit: "kg", category: "zelenjava", minQuantity: 1, costPerUnit: 3.0, supplier: "Local" },
  { name: "Kumare", unit: "kg", category: "zelenjava", minQuantity: 3, costPerUnit: 1.2, supplier: "Local" },
  { name: "Bučke", unit: "kg", category: "zelenjava", minQuantity: 3, costPerUnit: 1.5, supplier: "Local" },
  { name: "Jajčevec", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.0, supplier: "Local" },
  { name: "Solata (zelena)", unit: "kos", category: "zelenjava", minQuantity: 5, costPerUnit: 0.8, supplier: "Local" },
  { name: "Solata (ledena)", unit: "kos", category: "zelenjava", minQuantity: 5, costPerUnit: 1.0, supplier: "Local" },
  { name: "Solata (radikchio)", unit: "kos", category: "zelenjava", minQuantity: 2, costPerUnit: 1.5, supplier: "Local" },
  { name: "Solata (rukola)", unit: "kg", category: "zelenjava", minQuantity: 0.5, costPerUnit: 6.0, supplier: "Local" },
  { name: "Špinača (sveža)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.5, supplier: "Local" },
  { name: "Blitva", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.0, supplier: "Local" },
  { name: "Zelje (belo)", unit: "kg", category: "zelenjava", minQuantity: 5, costPerUnit: 0.8, supplier: "Local" },
  { name: "Zelje (rdeče)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 1.2, supplier: "Local" },
  { name: "Kislo zelje", unit: "kg", category: "zelenjava", minQuantity: 3, costPerUnit: 1.5, supplier: "Local" },
  { name: "Fižol (suhi)", unit: "kg", category: "zelenjava", minQuantity: 5, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Fižol (v konzervi)", unit: "kos", category: "zelenjava", minQuantity: 10, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Čičerika (suha)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Leča (rdeča)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 3.5, supplier: "Mercator" },
  { name: "Leča (zelena)", unit: "kg", category: "zelenjava", minQuantity: 1, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Gobe (šampinjoni)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 4.0, supplier: "Local" },
  { name: "Gobe (vrganji)", unit: "kg", category: "zelenjava", minQuantity: 0.5, costPerUnit: 15.0, supplier: "Local" },
  { name: "Gobe (shiitake)", unit: "kg", category: "zelenjava", minQuantity: 0.5, costPerUnit: 12.0, supplier: "Local" },
  { name: "Koruza (sladka)", unit: "kos", category: "zelenjava", minQuantity: 10, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Brokoli", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.5, supplier: "Local" },
  { name: "Cvetača", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 2.0, supplier: "Local" },
  { name: "Brsitovo ohrovt", unit: "kg", category: "zelenjava", minQuantity: 1, costPerUnit: 3.0, supplier: "Local" },
  { name: "Repo (rumena)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 1.0, supplier: "Local" },
  { name: "Repi (bele)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 1.0, supplier: "Local" },
  { name: "Buče (hokaido)", unit: "kg", category: "zelenjava", minQuantity: 2, costPerUnit: 1.5, supplier: "Local" },
  { name: "Avokado", unit: "kos", category: "zelenjava", minQuantity: 10, costPerUnit: 1.5, supplier: "Mercator" },

  // === SADJE ===
  { name: "Jabolka (idared)", unit: "kg", category: "sadje", minQuantity: 5, costPerUnit: 1.0, supplier: "Local" },
  { name: "Jabolka (zlati delishus)", unit: "kg", category: "sadje", minQuantity: 5, costPerUnit: 1.2, supplier: "Local" },
  { name: "Hruške", unit: "kg", category: "sadje", minQuantity: 3, costPerUnit: 1.5, supplier: "Local" },
  { name: "Banane", unit: "kg", category: "sadje", minQuantity: 5, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Pomaranče", unit: "kg", category: "sadje", minQuantity: 5, costPerUnit: 1.2, supplier: "Mercator" },
  { name: "Mandarine", unit: "kg", category: "sadje", minQuantity: 3, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Limone", unit: "kg", category: "sadje", minQuantity: 2, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Lime", unit: "kg", category: "sadje", minQuantity: 1, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Grozdje (belo)", unit: "kg", category: "sadje", minQuantity: 2, costPerUnit: 2.5, supplier: "Local" },
  { name: "Grozdje (rdeče)", unit: "kg", category: "sadje", minQuantity: 2, costPerUnit: 2.5, supplier: "Local" },
  { name: "Melona (rumena)", unit: "kos", category: "sadje", minQuantity: 2, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Lubenica", unit: "kos", category: "sadje", minQuantity: 1, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Jagode", unit: "kg", category: "sadje", minQuantity: 1, costPerUnit: 6.0, supplier: "Local" },
  { name: "Maline", unit: "kg", category: "sadje", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Local" },
  { name: "Borovnice", unit: "kg", category: "sadje", minQuantity: 0.5, costPerUnit: 7.0, supplier: "Local" },
  { name: "Češnje", unit: "kg", category: "sadje", minQuantity: 1, costPerUnit: 5.0, supplier: "Local" },
  { name: "Višnje", unit: "kg", category: "sadje", minQuantity: 1, costPerUnit: 4.5, supplier: "Local" },
  { name: "Breskve", unit: "kg", category: "sadje", minQuantity: 2, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Nektarine", unit: "kg", category: "sadje", minQuantity: 2, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Kivi", unit: "kg", category: "sadje", minQuantity: 2, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Ananas", unit: "kos", category: "sadje", minQuantity: 2, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Mango", unit: "kos", category: "sadje", minQuantity: 3, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Fige (sveže)", unit: "kg", category: "sadje", minQuantity: 0.5, costPerUnit: 6.0, supplier: "Local" },
  { name: "Orehi (lupinjeni)", unit: "kg", category: "sadje", minQuantity: 1, costPerUnit: 12.0, supplier: "Local" },
  { name: "Mandeljni (lupinjeni)", unit: "kg", category: "sadje", minQuantity: 1, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Lešniki", unit: "kg", category: "sadje", minQuantity: 0.5, costPerUnit: 10.0, supplier: "Local" },

  // === MLEČNI IZDELKI ===
  { name: "Mleko (3.2% maščobe)", unit: "l", category: "mlecni", minQuantity: 10, costPerUnit: 0.9, supplier: "Mlekarna Celeia" },
  { name: "Mleko (polno maščobno)", unit: "l", category: "mlecni", minQuantity: 5, costPerUnit: 1.0, supplier: "Mlekarna Celeia" },
  { name: "Mleko (posneto)", unit: "l", category: "mlecni", minQuantity: 5, costPerUnit: 0.8, supplier: "Mlekarna Celeia" },
  { name: "SmEtana (sladka 30%)", unit: "l", category: "mlecni", minQuantity: 2, costPerUnit: 2.5, supplier: "Mlekarna Celeia" },
  { name: "Smetana (kisla 20%)", unit: "kos", category: "mlecni", minQuantity: 10, costPerUnit: 0.8, supplier: "Mlekarna Celeia" },
  { name: "Jogurt (naravni)", unit: "kos", category: "mlecni", minQuantity: 10, costPerUnit: 0.6, supplier: "Mlekarna Celeia" },
  { name: "Jogurt (sadni)", unit: "kos", category: "mlecni", minQuantity: 10, costPerUnit: 0.7, supplier: "Mlekarna Celeia" },
  { name: "Kefir", unit: "l", category: "mlecni", minQuantity: 3, costPerUnit: 1.2, supplier: "Mlekarna Celeia" },
  { name: "Skuta (mehka)", unit: "kg", category: "mlecni", minQuantity: 2, costPerUnit: 4.0, supplier: "Mlekarna Celeia" },
  { name: "Skuta (trda)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 5.5, supplier: "Mlekarna Celeia" },
  { name: "Sir (mozzarella)", unit: "kg", category: "mlecni", minQuantity: 2, costPerUnit: 7.0, supplier: "Mlekarna Celeia" },
  { name: "Sir (parmezan)", unit: "kg", category: "mlecni", minQuantity: 0.5, costPerUnit: 18.0, supplier: "Mercator" },
  { name: "Sir (gorgonzola)", unit: "kg", category: "mlecni", minQuantity: 0.5, costPerUnit: 14.0, supplier: "Mercator" },
  { name: "Sir (feta)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Sir (bovški)", unit: "kg", category: "mlecni", minQuantity: 0.5, costPerUnit: 20.0, supplier: "Kraški" },
  { name: "Sir (nanoški)", unit: "kg", category: "mlecni", minQuantity: 0.5, costPerUnit: 15.0, supplier: "Mlekarna Celeia" },
  { name: "Sir (edamec)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 9.0, supplier: "Mlekarna Celeia" },
  { name: "Sir (gauda)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 8.5, supplier: "Mercator" },
  { name: "Sir (mascarpone)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 6.0, supplier: "Mercator" },
  { name: "Sir (ricotta)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Sir (pecorino)", unit: "kg", category: "mlecni", minQuantity: 0.5, costPerUnit: 22.0, supplier: "Mercator" },
  { name: "Maslo (nesoljeno)", unit: "kg", category: "mlecni", minQuantity: 2, costPerUnit: 7.0, supplier: "Mlekarna Celeia" },
  { name: "Maslo (soljeno)", unit: "kg", category: "mlecni", minQuantity: 1, costPerUnit: 6.5, supplier: "Mlekarna Celeia" },
  { name: "Jajca (M)", unit: "kos", category: "mlecni", minQuantity: 60, costPerUnit: 0.2, supplier: "Local" },
  { name: "Jajca (L)", unit: "kos", category: "mlecni", minQuantity: 60, costPerUnit: 0.25, supplier: "Local" },
  { name: "Jajca (prepacana)", unit: "l", category: "mlecni", minQuantity: 2, costPerUnit: 3.5, supplier: "Local" },

  // === ŽITA IN MOKE ===
  { name: "Moka (pšenična tip 500)", unit: "kg", category: "zita", minQuantity: 25, costPerUnit: 0.7, supplier: "Mlinotest" },
  { name: "Moka (pšenična tip 850)", unit: "kg", category: "zita", minQuantity: 10, costPerUnit: 0.8, supplier: "Mlinotest" },
  { name: "Moka (pšenična tip 1100)", unit: "kg", category: "zita", minQuantity: 5, costPerUnit: 0.9, supplier: "Mlinotest" },
  { name: "Moka (ostra)", unit: "kg", category: "zita", minQuantity: 10, costPerUnit: 0.8, supplier: "Mlinotest" },
  { name: "Moka (ajdova)", unit: "kg", category: "zita", minQuantity: 5, costPerUnit: 1.5, supplier: "Mlinotest" },
  { name: "Moka (koruzna)", unit: "kg", category: "zita", minQuantity: 5, costPerUnit: 1.2, supplier: "Mlinotest" },
  { name: "Moka (ražena)", unit: "kg", category: "zita", minQuantity: 3, costPerUnit: 1.3, supplier: "Mlinotest" },
  { name: "Moka (polnozrnata)", unit: "kg", category: "zita", minQuantity: 3, costPerUnit: 1.4, supplier: "Mlinotest" },
  { name: "Moka (piščančja)", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Moka (brez glutena)", unit: "kg", category: "zita", minQuantity: 1, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Drobnozrnata moka (tip 00)", unit: "kg", category: "zita", minQuantity: 10, costPerUnit: 1.0, supplier: "Mlinotest" },
  { name: "Krušne drobtine", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 1.0, supplier: "Mlinotest" },
  { name: "Polenta", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 1.2, supplier: "Mercator" },
  { name: "Riž (beli dolgozrnati)", unit: "kg", category: "zita", minQuantity: 5, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Riž (basmati)", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Riž (arborio)", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Riž (okrogli)", unit: "kg", category: "zita", minQuantity: 3, costPerUnit: 1.3, supplier: "Mercator" },
  { name: "Riž (rjavi)", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 1.8, supplier: "Mercator" },
  { name: "Testenine (špageti)", unit: "kg", category: "zita", minQuantity: 5, costPerUnit: 1.5, supplier: "Mlinotest" },
  { name: "Testenine (penne)", unit: "kg", category: "zita", minQuantity: 3, costPerUnit: 1.5, supplier: "Mlinotest" },
  { name: "Testenine (fusilli)", unit: "kg", category: "zita", minQuantity: 3, costPerUnit: 1.5, supplier: "Mlinotest" },
  { name: "Testenine (fettuccine)", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 2.0, supplier: "Mlinotest" },
  { name: "Testenine (lasagne)", unit: "kos", category: "zita", minQuantity: 5, costPerUnit: 2.0, supplier: "Mlinotest" },
  { name: "Žlikrofi (surovi)", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 5.0, supplier: "Local" },
  { name: "Kruh (beli)", unit: "kos", category: "zita", minQuantity: 5, costPerUnit: 1.5, supplier: "Pekarna" },
  { name: "Kruh (črni)", unit: "kos", category: "zita", minQuantity: 5, costPerUnit: 1.8, supplier: "Pekarna" },
  { name: "Kruh (polnozrnati)", unit: "kos", category: "zita", minQuantity: 3, costPerUnit: 2.0, supplier: "Pekarna" },
  { name: "Pica testo (surovo)", unit: "kos", category: "zita", minQuantity: 10, costPerUnit: 1.0, supplier: "Pekarna" },
  { name: "Ovseni kosmiči", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Kuskus", unit: "kg", category: "zita", minQuantity: 2, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Bulgur", unit: "kg", category: "zita", minQuantity: 1, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Quinoa", unit: "kg", category: "zita", minQuantity: 1, costPerUnit: 5.0, supplier: "Mercator" },

  // === OLJA IN MAŠČOBE ===
  { name: "Olje (sončnično)", unit: "l", category: "olja", minQuantity: 10, costPerUnit: 1.8, supplier: "Mercator" },
  { name: "Olje (olivno extra deviško)", unit: "l", category: "olja", minQuantity: 5, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Olje (olivno)", unit: "l", category: "olja", minQuantity: 5, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Olje (repično)", unit: "l", category: "olja", minQuantity: 5, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Olje (čičerikovo)", unit: "l", category: "olja", minQuantity: 2, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Olje (sezamovo)", unit: "l", category: "olja", minQuantity: 1, costPerUnit: 6.0, supplier: "Mercator" },
  { name: "Olje (orehovo)", unit: "l", category: "olja", minQuantity: 0.5, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Olje (avokadovo)", unit: "l", category: "olja", minQuantity: 0.5, costPerUnit: 10.0, supplier: "Mercator" },
  { name: "Margarina", unit: "kg", category: "olja", minQuantity: 2, costPerUnit: 2.5, supplier: "Mercator" },
  { name: "Kokosovo olje", unit: "kg", category: "olja", minQuantity: 1, costPerUnit: 8.0, supplier: "Mercator" },

  // === ZAČIMBE IN SOL ===
  { name: "Sol (morska)", unit: "kg", category: "zacimbe", minQuantity: 2, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Sol (kamena)", unit: "kg", category: "zacimbe", minQuantity: 2, costPerUnit: 0.5, supplier: "Mercator" },
  { name: "Popper (črn mleti)", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Popper (beli)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 20.0, supplier: "Mercator" },
  { name: "Popper (rozice)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 18.0, supplier: "Mercator" },
  { name: "Paprika (sladka mleta)", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Paprika (pikantna)", unit: "kg", category: "zacimbe", minQuantity: 0.3, costPerUnit: 9.0, supplier: "Mercator" },
  { name: "Kumina", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Koriander (seme)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 10.0, supplier: "Mercator" },
  { name: "Koriander (listi)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 8.0, supplier: "Local" },
  { name: "Origano (suhi)", unit: "kg", category: "zacimbe", minQuantity: 0.3, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Bazilika (suha)", unit: "kg", category: "zacimbe", minQuantity: 0.3, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Bazilika (sveža)", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Local" },
  { name: "Timijan (suhi)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 18.0, supplier: "Mercator" },
  { name: "Rožmarin (suhi)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Rožmarin (sveži)", unit: "kg", category: "zacimbe", minQuantity: 0.3, costPerUnit: 10.0, supplier: "Local" },
  { name: "Žajblj (sveži)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 12.0, supplier: "Local" },
  { name: "Peteršilj (sveži)", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 4.0, supplier: "Local" },
  { name: "Drobnjak (sveži)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 6.0, supplier: "Local" },
  { name: "Lovorjev list", unit: "kg", category: "zacimbe", minQuantity: 0.1, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Cimet", unit: "kg", category: "zacimbe", minQuantity: 0.1, costPerUnit: 18.0, supplier: "Mercator" },
  { name: "Klinčki", unit: "kg", category: "zacimbe", minQuantity: 0.05, costPerUnit: 25.0, supplier: "Mercator" },
  { name: "Muškatni orešček", unit: "kg", category: "zacimbe", minQuantity: 0.1, costPerUnit: 30.0, supplier: "Mercator" },
  { name: "Šafran", unit: "g", category: "zacimbe", minQuantity: 10, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Vanilija (strok)", unit: "kos", category: "zacimbe", minQuantity: 5, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Vanilijin sladkor", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Curry (v prahu)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Kurkuma", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 10.0, supplier: "Mercator" },
  { name: "Chili (v prahu)", unit: "kg", category: "zacimbe", minQuantity: 0.2, costPerUnit: 14.0, supplier: "Mercator" },
  { name: "Chili (sveži)", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Local" },
  { name: "Ingver (sveži)", unit: "kg", category: "zacimbe", minQuantity: 0.5, costPerUnit: 6.0, supplier: "Mercator" },

  // === SLADKOR IN SLADILA ===
  { name: "Sladkor (beli)", unit: "kg", category: "sladkor", minQuantity: 5, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Sladkor (rjavi)", unit: "kg", category: "sladkor", minQuantity: 2, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Sladkor v prahu", unit: "kg", category: "sladkor", minQuantity: 1, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Med (cvetlični)", unit: "kg", category: "sladkor", minQuantity: 1, costPerUnit: 8.0, supplier: "Local" },
  { name: "Med (kostanjev)", unit: "kg", category: "sladkor", minQuantity: 0.5, costPerUnit: 12.0, supplier: "Local" },
  { name: "Agavin sirup", unit: "l", category: "sladkor", minQuantity: 1, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Javorjev sirup", unit: "l", category: "sladkor", minQuantity: 0.5, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Kakav (v prahu)", unit: "kg", category: "sladkor", minQuantity: 1, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Čokolada (temna 70%)", unit: "kg", category: "sladkor", minQuantity: 1, costPerUnit: 10.0, supplier: "Mercator" },
  { name: "Čokolada (mlečna)", unit: "kg", category: "sladkor", minQuantity: 1, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Čokolada (bela)", unit: "kg", category: "sladkor", minQuantity: 0.5, costPerUnit: 9.0, supplier: "Mercator" },

  // === KAVA IN ČAJ ===
  { name: "Kava (zrna arabica)", unit: "kg", category: "kava", minQuantity: 4, costPerUnit: 18.0, supplier: "Barcaffe" },
  { name: "Kava (zrna robusta)", unit: "kg", category: "kava", minQuantity: 2, costPerUnit: 14.0, supplier: "Barcaffe" },
  { name: "Kava (mleta)", unit: "kg", category: "kava", minQuantity: 2, costPerUnit: 16.0, supplier: "Barcaffe" },
  { name: "Kava (instant)", unit: "kg", category: "kava", minQuantity: 1, costPerUnit: 12.0, supplier: "Barcaffe" },
  { name: "Kavne kapsule", unit: "kos", category: "kava", minQuantity: 50, costPerUnit: 0.3, supplier: "Barcaffe" },
  { name: "Čaj (črni)", unit: "kos", category: "kava", minQuantity: 50, costPerUnit: 0.1, supplier: "Mercator" },
  { name: "Čaj (zeleni)", unit: "kos", category: "kava", minQuantity: 30, costPerUnit: 0.12, supplier: "Mercator" },
  { name: "Čaj (sadni)", unit: "kos", category: "kava", minQuantity: 30, costPerUnit: 0.1, supplier: "Mercator" },
  { name: "Čaj (kamilice)", unit: "kos", category: "kava", minQuantity: 20, costPerUnit: 0.1, supplier: "Mercator" },
  { name: "Čaj (meta)", unit: "kos", category: "kava", minQuantity: 20, costPerUnit: 0.1, supplier: "Mercator" },

  // === BREZALKOHOLNE PIJAČE ===
  { name: "Radenska (mineralna 0.5l)", unit: "kos", category: "pijaca", minQuantity: 48, costPerUnit: 0.5, supplier: "Radenska" },
  { name: "Radenska (mineralna 1l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.8, supplier: "Radenska" },
  { name: "Radenska (naravna 0.5l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.5, supplier: "Radenska" },
  { name: "Coca-Cola (0.25l)", unit: "kos", category: "pijaca", minQuantity: 48, costPerUnit: 0.6, supplier: "Coca-Cola" },
  { name: "Coca-Cola (0.5l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.9, supplier: "Coca-Cola" },
  { name: "Coca-Cola Zero (0.25l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.6, supplier: "Coca-Cola" },
  { name: "Coca-Cola Zero (0.5l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.9, supplier: "Coca-Cola" },
  { name: "Fanta (0.25l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.6, supplier: "Coca-Cola" },
  { name: "Sprite (0.25l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.6, supplier: "Coca-Cola" },
  { name: "Pivo (brezalkoholno)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.8, supplier: "Laško" },
  { name: "Sok (pomarančni 0.2l)", unit: "kos", category: "pijaca", minQuantity: 48, costPerUnit: 0.4, supplier: "Fructal" },
  { name: "Sok (jabolčni 0.2l)", unit: "kos", category: "pijaca", minQuantity: 48, costPerUnit: 0.4, supplier: "Fructal" },
  { name: "Sok (multivitamin 0.2l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.45, supplier: "Fructal" },
  { name: "Sok (breskov 0.2l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.4, supplier: "Fructal" },
  { name: "Sok (paradižnikov 0.2l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.4, supplier: "Fructal" },
  { name: "Sok (grenivkin 0.2l)", unit: "kos", category: "pijaca", minQuantity: 12, costPerUnit: 0.5, supplier: "Fructal" },
  { name: "Sok (brusnični 0.2l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.5, supplier: "Fructal" },
  { name: "Ledeni čaj (breskov 0.25l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.6, supplier: "Fructal" },
  { name: "Ledeni čaj (limonin 0.25l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.6, supplier: "Fructal" },
  { name: "Voda (nesladkana 0.5l)", unit: "kos", category: "pijaca", minQuantity: 48, costPerUnit: 0.4, supplier: "Radenska" },
  { name: "Voda (okisana 0.5l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.6, supplier: "Radenska" },
  { name: "Energijska pijača (0.25l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Tonic (0.2l)", unit: "kos", category: "pijaca", minQuantity: 24, costPerUnit: 0.7, supplier: "Mercator" },
  { name: "Ginger Ale (0.2l)", unit: "kos", category: "pijaca", minQuantity: 12, costPerUnit: 0.7, supplier: "Mercator" },
  { name: "Bitter Lemon (0.2l)", unit: "kos", category: "pijaca", minQuantity: 12, costPerUnit: 0.7, supplier: "Mercator" },
  { name: "Soda (0.2l)", unit: "kos", category: "pijaca", minQuantity: 48, costPerUnit: 0.3, supplier: "Radenska" },
  { name: "Aperol (0.7l)", unit: "kos", category: "pijaca", minQuantity: 6, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Campari (0.7l)", unit: "kos", category: "pijaca", minQuantity: 3, costPerUnit: 18.0, supplier: "Mercator" },

  // === ALKOHOLNE PIJAČE ===
  { name: "Pivo Laško (0.5l steklenica)", unit: "kos", category: "alkohol", minQuantity: 48, costPerUnit: 0.8, supplier: "Laško" },
  { name: "Pivo Laško (0.33l pločevka)", unit: "kos", category: "alkohol", minQuantity: 48, costPerUnit: 0.7, supplier: "Laško" },
  { name: "Pivo Union (0.5l steklenica)", unit: "kos", category: "alkohol", minQuantity: 48, costPerUnit: 0.8, supplier: "Union" },
  { name: "Pivo Union (0.33l pločevka)", unit: "kos", category: "alkohol", minQuantity: 48, costPerUnit: 0.7, supplier: "Union" },
  { name: "Pivo Laško Zlatorog (0.5l)", unit: "kos", category: "alkohol", minQuantity: 24, costPerUnit: 1.0, supplier: "Laško" },
  { name: "Pivo Laško Club (0.33l)", unit: "kos", category: "alkohol", minQuantity: 24, costPerUnit: 0.9, supplier: "Laško" },
  { name: "Pivo (brez glutena)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 1.2, supplier: "Laško" },
  { name: "Pivo (temno)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 1.1, supplier: "Laško" },
  { name: "Pivo (IPA)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 1.3, supplier: "Local" },
  { name: "Vino Laški beli (0.75l)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 5.0, supplier: "Vinska klet" },
  { name: "Vino Laški beli (sod 5l)", unit: "kos", category: "alkohol", minQuantity: 2, costPerUnit: 15.0, supplier: "Vinska klet" },
  { name: "Vino Refošk (0.75l)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 6.0, supplier: "Vinska klet" },
  { name: "Vino Refošk (sod 5l)", unit: "kos", category: "alkohol", minQuantity: 2, costPerUnit: 18.0, supplier: "Vinska klet" },
  { name: "Vino Modra Frankinja (0.75l)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 6.0, supplier: "Vinska klet" },
  { name: "Vino Modra Frankinja (sod 5l)", unit: "kos", category: "alkohol", minQuantity: 2, costPerUnit: 18.0, supplier: "Vinska klet" },
  { name: "Vino Cviček (0.75l)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 4.5, supplier: "Vinska klet" },
  { name: "Vino Cviček (sod 5l)", unit: "kos", category: "alkohol", minQuantity: 2, costPerUnit: 13.0, supplier: "Vinska klet" },
  { name: "Vino Malvazija (0.75l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 7.0, supplier: "Vinska klet" },
  { name: "Vino Sauvignon (0.75l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 7.5, supplier: "Vinska klet" },
  { name: "Vino Chardonnay (0.75l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 8.0, supplier: "Vinska klet" },
  { name: "Vino Rumeni muškat (0.75l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 7.5, supplier: "Vinska klet" },
  { name: "Vino Peneče (0.75l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 8.0, supplier: "Vinska klet" },
  { name: "Prosecco (0.75l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 7.0, supplier: "Mercator" },
  { name: "Peneče vino (0.2l)", unit: "kos", category: "alkohol", minQuantity: 12, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Žganje slivovka (0.5l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 8.0, supplier: "Local" },
  { name: "Žganje viljamovka (0.5l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 9.0, supplier: "Local" },
  { name: "Žganje hruškovo (0.5l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 8.5, supplier: "Local" },
  { name: "Žganje jabolčno (0.5l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 8.0, supplier: "Local" },
  { name: "Vodka (0.7l)", unit: "kos", category: "alkohol", minQuantity: 6, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Gin (0.7l)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 18.0, supplier: "Mercator" },
  { name: "Rum (0.7l)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Whisky (0.7l)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 22.0, supplier: "Mercator" },
  { name: "Konjak (0.7l)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 20.0, supplier: "Mercator" },
  { name: "Likör (jagodni)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Amaretto (0.7l)", unit: "kos", category: "alkohol", minQuantity: 2, costPerUnit: 15.0, supplier: "Mercator" },
  { name: "Baileys (0.7l)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 18.0, supplier: "Mercator" },
  { name: "Jägermeister (0.7l)", unit: "kos", category: "alkohol", minQuantity: 3, costPerUnit: 20.0, supplier: "Mercator" },
  { name: "Tekila (0.7l)", unit: "kos", category: "alkohol", minQuantity: 2, costPerUnit: 22.0, supplier: "Mercator" },

  // === DODATKI IN OMAKE ===
  { name: "Majoneza", unit: "kg", category: "omake", minQuantity: 2, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Ketchup", unit: "kg", category: "omake", minQuantity: 2, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Gorčica (ostro)", unit: "kg", category: "omake", minQuantity: 1, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Gorčica (dijon)", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 6.0, supplier: "Mercator" },
  { name: "Hren", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Tartar omaka", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Sojina omaka", unit: "l", category: "omake", minQuantity: 1, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Worcestershire omaka", unit: "l", category: "omake", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Tabasco", unit: "kos", category: "omake", minQuantity: 3, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Balzamični kis", unit: "l", category: "omake", minQuantity: 1, costPerUnit: 6.0, supplier: "Mercator" },
  { name: "Jabolčni kis", unit: "l", category: "omake", minQuantity: 2, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Vinski kis (beli)", unit: "l", category: "omake", minQuantity: 1, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Vinski kis (rdeči)", unit: "l", category: "omake", minQuantity: 1, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Pesto (bazilikin)", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 10.0, supplier: "Mercator" },
  { name: "Peštan (tahini)", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Humus", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 4.0, supplier: "Mercator" },
  { name: "Oljke (zelene)", unit: "kg", category: "omake", minQuantity: 1, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Oljve (črne)", unit: "kg", category: "omake", minQuantity: 1, costPerUnit: 5.0, supplier: "Mercator" },
  { name: "Kapre", unit: "kg", category: "omake", minQuantity: 0.2, costPerUnit: 12.0, supplier: "Mercator" },
  { name: "Sun-dried paradižnik", unit: "kg", category: "omake", minQuantity: 0.5, costPerUnit: 10.0, supplier: "Mercator" },

  // === KONZERVIRANA ŽIVILA ===
  { name: "Paradižnik (pelati v konzervi)", unit: "kos", category: "konzerve", minQuantity: 20, costPerUnit: 1.2, supplier: "Mercator" },
  { name: "Paradižnikova omaka (passata)", unit: "l", category: "konzerve", minQuantity: 10, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Tuna v olju", unit: "kos", category: "konzerve", minQuantity: 20, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Tuna v vodi", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Ananas (konzerviran)", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Breskve (konzervirane)", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 1.5, supplier: "Mercator" },
  { name: "Kukuruz (konzerviran)", unit: "kos", category: "konzerve", minQuantity: 15, costPerUnit: 0.8, supplier: "Mercator" },
  { name: "Grašak (konzerviran)", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 0.8, supplier: "Mercator" },
  { name: "Fižol (rdeči konzerviran)", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Fižol (beli konzerviran)", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Leča (konzervirana)", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Kokosovo mleko", unit: "kos", category: "konzerve", minQuantity: 10, costPerUnit: 1.5, supplier: "Mercator" },

  // === OSNOVNA ŽIVILA ===
  { name: "Kvas (suhi)", unit: "kos", category: "osnove", minQuantity: 10, costPerUnit: 0.5, supplier: "Mercator" },
  { name: "Kvas (sveži)", unit: "kos", category: "osnove", minQuantity: 5, costPerUnit: 0.3, supplier: "Mercator" },
  { name: "Pekovski kvas", unit: "kg", category: "osnove", minQuantity: 0.5, costPerUnit: 5.0, supplier: "Mlinotest" },
  { name: "Gelatina (listi)", unit: "kos", category: "osnove", minQuantity: 20, costPerUnit: 0.2, supplier: "Mercator" },
  { name: "Agar agar", unit: "kg", category: "osnove", minQuantity: 0.1, costPerUnit: 30.0, supplier: "Mercator" },
  { name: "Škrob (koruzni)", unit: "kg", category: "osnove", minQuantity: 1, costPerUnit: 2.0, supplier: "Mercator" },
  { name: "Škrob (krompirjev)", unit: "kg", category: "osnove", minQuantity: 0.5, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Pecilni prašek", unit: "kos", category: "osnove", minQuantity: 10, costPerUnit: 0.5, supplier: "Mercator" },
  { name: "Soda bikarbona", unit: "kg", category: "osnove", minQuantity: 0.2, costPerUnit: 3.0, supplier: "Mercator" },
  { name: "Vinska kislina", unit: "kg", category: "osnove", minQuantity: 0.1, costPerUnit: 8.0, supplier: "Mercator" },
  { name: "Želatina v prahu", unit: "kos", category: "osnove", minQuantity: 10, costPerUnit: 1.0, supplier: "Mercator" },
  { name: "Vafelj (za sladoled)", unit: "kos", category: "osnove", minQuantity: 100, costPerUnit: 0.05, supplier: "Mercator" },

  // === EMBALAŽA ===
  { name: "Plastična posoda (0.5l)", unit: "kos", category: "embalaza", minQuantity: 100, costPerUnit: 0.1, supplier: "Embalaža" },
  { name: "Plastična posoda (1l)", unit: "kos", category: "embalaza", minQuantity: 50, costPerUnit: 0.15, supplier: "Embalaža" },
  { name: "Alu folija", unit: "kos", category: "embalaza", minQuantity: 5, costPerUnit: 2.0, supplier: "Embalaža" },
  { name: "Prosojna folija", unit: "kos", category: "embalaza", minQuantity: 5, costPerUnit: 1.5, supplier: "Embalaža" },
  { name: "Papir za peko", unit: "kos", category: "embalaza", minQuantity: 5, costPerUnit: 2.0, supplier: "Embalaža" },
  { name: "Vrečke (za vračunice)", unit: "kos", category: "embalaza", minQuantity: 500, costPerUnit: 0.02, supplier: "Embalaža" },
  { name: "Slamice (papirnate)", unit: "kos", category: "embalaza", minQuantity: 500, costPerUnit: 0.03, supplier: "Embalaža" },
  { name: "Mešalke", unit: "kos", category: "embalaza", minQuantity: 500, costPerUnit: 0.02, supplier: "Embalaža" },
  { name: "Robčki (papirnati)", unit: "kos", category: "embalaza", minQuantity: 500, costPerUnit: 0.02, supplier: "Embalaža" },
];

// Vrne kategorije iz kataloga
export const CATALOG_CATEGORIES = [
  { id: "meso", label: "Meso in mesnine", icon: "🥩" },
  { id: "ribe", label: "Ribe in morski sadeži", icon: "🐟" },
  { id: "zelenjava", label: "Zelenjava", icon: "🥕" },
  { id: "sadje", label: "Sadje", icon: "🍎" },
  { id: "mlecni", label: "Mlečni izdelki", icon: "🥛" },
  { id: "zita", label: "Žita in moke", icon: "🌾" },
  { id: "olja", label: "Olja in maščobe", icon: "🫒" },
  { id: "zacimbe", label: "Začimbe in sol", icon: "🧂" },
  { id: "sladkor", label: "Sladkor in sladila", icon: "🍯" },
  { id: "kava", label: "Kava in čaj", icon: "☕" },
  { id: "pijaca", label: "Brezalkoholne pijače", icon: "🥤" },
  { id: "alkohol", label: "Alkoholne pijače", icon: "🍷" },
  { id: "omake", label: "Omake in dodatki", icon: "🥫" },
  { id: "konzerve", label: "Konzervirana živila", icon: "🥫" },
  { id: "osnove", label: "Osnovna živila", icon: "📦" },
  { id: "embalaza", label: "Embalaža", icon: "📦" },
];

// Preštej artikle po kategorijah
export function getCatalogStats() {
  const stats: Record<string, number> = {};
  for (const item of FOOD_CATALOG) {
    stats[item.category] = (stats[item.category] || 0) + 1;
  }
  return stats;
}
